### ISSUE TITLE
Provide better error reporting when attempting to setup

### ISSUE THREAD

**Issue by Inrixia** [alvgaona/cloudflare-discord-bot#11]
### Summary

Currently if a error is encountered when attempting to setup a command the only info returned is that setup failed on that command as seen here:
https://github.com/alvgaona/cloudflare-discord-bot/blob/7adf8bc5219d5d4109b708e17924b7132c054a7b/src/setup.ts#L91-L99

### Intended Outcome

Provide information from error encountered so its actually possible to debug issues.

### How will it work?

Just add the error.message & error.stack to the result. Ideally return a json object with these as fields.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alvgaona** [comment]
Thank you so much. This is actually good. 😄
