### ISSUE TITLE
Switch to using discord-api-types

### ISSUE THREAD

**Issue by Inrixia** [alvgaona/cloudflare-discord-bot#16]
### Summary

Currently all the types used in this project are manfully written and need to be maintained by this project.
There is a npm library with TS support for discord api types called [discord-api-types](https://www.npmjs.com/package/discord-api-types). This contains both typescript definitions and actual values and is updated inline with the discord api.

Note the currently this projects types are outdated.

### Intended Outcome
Ideally this project should switch to using this library for types. 

### How will it work?
Just swap existing types with those from the library.
I would be happy to work on a PR to implemented the requested changes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alvgaona** [comment]
@Inrixia I'll be taking care of it this week.

**Comment by Inrixia** [comment]
Sweet, though I suggest sorting https://github.com/alvgaona/cloudflare-discord-bot/pull/14 first as once thats done I can open a PR for this.

I have done a bunch of work already adding types but its upstream from https://github.com/alvgaona/cloudflare-discord-bot/pull/14

**Comment by alvgaona** [comment]
@Inrixia it looks like #14 has all this taken care of, right?

**Comment by Inrixia** [comment]
Yes
