### ISSUE TITLE
Typo on import

### ISSUE THREAD

**Issue by lugui1998** [alvgaona/cloudflare-discord-bot#18]
### Description

index.ts imports helloHanlder instead of helloHandler

### Reproducibility

Install this per README instructions

### Version

0.0.1 (latest)

### What browsers are you seeing the problem on?

Microsoft Edge

### Log output

```shell
none, it cannot compile
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alvgaona** [comment]
Thanks!
