### ISSUE TITLE
npm installs without any files

### ISSUE THREAD

**Issue by julianclatro** [alvgaona/cloudflare-discord-bot#3]
### Description

I'm not sure if is because I don't have ssh access or it just needs the dist folder to be committed to work.
After forking and committing the dist folder everything works like charms, thanks!

![Screen Shot 2022-02-17 at 10 05 52](https://user-images.githubusercontent.com/6716921/154489476-d3ec27ae-57e1-448e-90a3-2b21ac79a644.png)

### Version

0.0.1 (latest)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alvgaona** [comment]
Published and fixed.
