### ISSUE TITLE
New project inquiry for revolt bots 

### ISSUE THREAD

**Issue by AlecMcCutcheon** [alvgaona/cloudflare-discord-bot#8]
### Summary

I was wondering if it would be possible for you to make a cloudflare-revolt-bot project

https://developers.revolt.chat/stack/revolt.js/guide/overview

### Intended Outcome

framework to make revolt bots using cloudflare workers

### How will it work?

https://developers.revolt.chat/stack/revolt.js/guide/discord_js_migration

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlecMcCutcheon** [comment]
Also they could really use some help in other areas as well, if you'd ever consider contributing, that would be awesome

**Comment by alvgaona** [comment]
Hi@AlecMcCutcheon, thanks for reaching out. Revolt looks cool, I'll take a look at this invitation. 😄
