### ISSUE TITLE
Don't use 301 redirects

### ISSUE THREAD

**Issue by Inrixia** [alvgaona/cloudflare-discord-bot#9]
### Description

https://github.com/alvgaona/cloudflare-discord-bot/blob/7adf8bc5219d5d4109b708e17924b7132c054a7b/src/authorize.ts#L13-L16
301 redirects are permanent and browsers will hard cache them to the point of not even touching the origin when encountering that url again. This means that if the bot client id changes its impossible for clients to get the new id without manually clearing browser data (and even then that sometimes wont work).

Instead you should use [302](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302) 

### Reproducibility

Create a bot, publish the worker and go to its base url, change the bot's client id/recreate it, go to its base url and get the wrong client id.

### Version

0.0.1 (latest)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alvgaona** [comment]
@gzalo do you want to do it?

**Comment by Inrixia** [comment]
I can handle this in another pr if you like

**Comment by Inrixia** [comment]
Ill open a PR for this once the prettier changes have been merged so as to avoid further confusion
